services:
  - type: web
    name: stocksense-api
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHONPATH
        value: "."
      - key: PYTHON_VERSION
        value: "3.11.0"